# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b38fbae62634999b1afac49bbf951878"
name = "Whatflow_New_Test"
application_url = "https://whatflow-alpha.vercel.app"
embedded = true

[webhooks]
api_version = "2024-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,write_checkouts,read_customers,write_customers,read_fulfillments,write_fulfillments,read_orders,write_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://whatflow-alpha.vercel.app/api/auth/callback",
  "https://whatflow-alpha.vercel.app/api/auth/tokens",
  "https://api.whatomatic.com/Api/auth/shopify/callback"
]