# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "75863c3625995c738abd1c50caa3e20b"
name = "whatflow_test"
application_url = "https://whatflow-alpha.vercel.app/"
embedded = true

[webhooks]
api_version = "2024-01"

[[webhooks.subscriptions]]
topics = [ "orders/create", "orders/cancelled" ]
uri = "https://backend-wfmy.onrender.com/api/webhooks/shopify"

[[webhooks.subscriptions]]
topics = [ "checkouts/create", "fulfillments/update" ]
uri = "https://backend-wfmy.onrender.com/api/webhooks/shopify"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_checkouts,read_fulfillments,read_customers"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://whatflow-alpha.vercel.app/api/auth/callback",
  "https://whatflow-alpha.vercel.app/api/auth/tokens"
]
